spring:
  application:
    name: spring-ai-rag
  ai:
    openai:
      # a run configban van
      api-key: ${OPENAI_API_KEY}
sfg:
  aiapp:
    vectorStorePath: 'C:\temp\vectorstore.json'
    documentsToLoad:
      - classpath:/movies500.csv
logging:
  level:
    org:
      springframework:
        web: trace