### Ask question

POST http://localhost:8080/ask
Content-Type: application/json

{ "question" : "What is the movie Titanic about?" }

### Ask question

POST http://localhost:8080/ask
Content-Type: application/json

{ "question" : "What do you know about the movie Toy Story 4?" }